# Generated by Django 5.1.6 on 2025-03-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('inquiry_type', models.CharField(choices=[('general', 'General Inquiry'), ('feedback', 'Feedback'), ('complaint', 'Complaint'), ('suggestion', 'Suggestion'), ('destination', 'Destination Comment'), ('activity', 'Activity Comment'), ('event', 'Event Comment')], default='general', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('reference_id', models.PositiveIntegerField(blank=True, help_text='ID of the item being commented on, if applicable', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
