# Generated by Django 5.1.6 on 2025-03-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culture',
            name='categories',
        ),
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.CharField(blank=True, help_text="Approximate duration of the activity (e.g., '2-3 hours', 'Half day')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='location_name',
            field=models.CharField(blank=True, help_text='Physical location name, different from map link', max_length=200, null=True),
        ),
    ]
