# Generated by Django 5.1.7 on 2025-04-03 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_remove_culture_categories_activity_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='explore.activity')),
                ('culture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='explore.culture')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='explore.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('destination__isnull', False), ('activity__isnull', False), ('culture__isnull', False), _connector='OR'), name='favorite_has_item'), models.UniqueConstraint(condition=models.Q(('destination__isnull', False)), fields=('user', 'destination'), name='unique_user_destination'), models.UniqueConstraint(condition=models.Q(('activity__isnull', False)), fields=('user', 'activity'), name='unique_user_activity'), models.UniqueConstraint(condition=models.Q(('culture__isnull', False)), fields=('user', 'culture'), name='unique_user_culture')],
            },
        ),
    ]
